### PR TITLE
Remove the need for the double terraform apply

### PR DESCRIPTION
**Pull request by dgubitosi**
These changes remove the need for the double terraform apply.  The ps-template module ingests the contents of the policy_sentry output using a local-file data source.  It has a dependency on the null resource.  I also used a local-file resource to write the template to disk and altered the policy_sentry command accordingly.  The policy contents can now be directly referenced by the iam-policies module.  I changed the template-file data source to an aws_iam_policy_document data source but the policy contents could be directly consumed by the aws_iam_policy resource.  

For discussion, I have an alternative version of this change in this branch:
https://github.com/dgubitosi/terraform-aws-policy-sentry/tree/external-data-source

I think this a more elegant but also more radical solution.  Replacing the null resource with an external data source required changes to policy_sentry to output the policy in a way that it could be ingested.  It's a relatively minor change to add a flag so that policy_sentry would output as a json encapsulated base64 string.

My changes to policy_sentry are in this branch:
https://github.com/dgubitosi/policy_sentry/tree/output-base64

### CODE REVIEW

**Comment by kmcquade** [comment]
Hey @dgubitosi, looks **really** cool. I'd like to test this out. 

> My changes to policy_sentry are in this branch: https://github.com/dgubitosi/policy_sentry/tree/output-base64

Can you submit that as a PR to Policy Sentry? 

And before you do so... perhaps combine these two different click options into `type=click.Choice(["yaml", "json", "base64"])`. Seems cleaner. 

```
@click.option(
    "--fmt",
    type=click.Choice(["yaml", "json"]),
    default="json",
    required=False,
    help='Format output as YAML or JSON. Defaults to "json"',
)
@click.option(
    "--output-base64",
    required=False,
    is_flag=True,
    help='Outputs json { "base64": "base64-encoded-policy" }'
)
```

https://github.com/dgubitosi/policy_sentry/blob/c4f2f033d7162b85ba0b78fc50e9c545f711cd46/policy_sentry/command/write_policy.py#L41-L46

Then we can look at merging this one

**Comment by kmcquade** [comment]
> I think this a more elegant but also more radical solution.

I love elegant and radical solutions :) 

Btw, if you want to chat at all, feel free to DM me on Twitter, the Cloud Security Forum slack, or the Gitter channel for Policy Sentry.

**Comment by dgubitosi** [comment]
That's a good idea.  I will do that.  And I'm now just realizing that the base64 may not even be necessary.  The terraform external data source's limitation is that it can only unmarshal simple json key:value strings. It can't be a nested value. Using base64 was just a simple way to stringify the policy.  However I think this would work if the policy was a json string encapsulated in json. It just looks a bit funny because all the inner quotes are escaped.  I'm going to experiment with that using fmt terraform because i have no other sensible name for it.

**Comment by dgubitosi** [comment]
Closing this request since its superseded by the other one.

**Pull request closed without merging**
