### PR TITLE
Use Terraform external data source

### PR DESCRIPTION
**Pull request by dgubitosi**
This solution removes the need for the double apply but requires changes to policy_sentry so that it can output the policy in a way that it can be ingested by a Terraform external data source.

The changes to policy_sentry are currently in this branch:
https://github.com/dgubitosi/policy_sentry/tree/terraform

--fmt terraform outputs the following which can be ingested by referencing the policy key
{ "policy": escaped-json-string }
--minimize -1 is required because the external data source errors if one of a parameter is null, and escapes all the parameters leading to "--minimize\ 0" in the other case

@kmcquade: Let me know what you think. Do you have a better name for the new format? I really don't like terraform but I could not think of anything better.  Regarding a PR to policy_sentry, I'm not sure how to build a unit test for this.  The write unit tests all use the library function write_policy_with_template() which only produces the policy.

### CODE REVIEW

**Comment by kmcquade** [comment]
> --minimize -1 is required because the external data source errors if one of a parameter is null, and escapes all the parameters leading to "--minimize\ 0" in the other case

I was thinking about changing the minimize flag to be a straight up flag instead of passing the 0. Passing the number seems unnecessary and it is easier to abstract that for the user. Of course, I'd want to introduce that change in a new minor version. I can make a note that we will keep that update in sync with this one. What do you think?

> Regarding a PR to policy_sentry, I'm not sure how to build a unit test for this. The write unit tests all use the library function write_policy_with_template() which only produces the policy.

In Policy Sentry, we use Click instead of argparse. I wrote most of the unit tests before I realized that Click had a [CliRunner.invoke](https://click.palletsprojects.com/en/7.x/testing/) method that allows you to run the command line script in isolation. You **could try testing it with that. 

Personally, I think the Python code change itself is super straightforward and doesn't require a unit test. Although I should introduce Click testing anyway. I'd be okay with merging the Python code as-is. But first, could you update the documentation to reflect the changes you introduce? The docs would end up here. https://policy-sentry.readthedocs.io/en/latest/other/terraform/

It should significantly reduce the size of the Readme for this Terraform module.

> Do you have a better name for the new format? I really don't like terraform but I could not think of anything better

Yeah, I can't think of anything better either. Let's keep it like this.

We can also make it a bit more obvious by moving this Terraform module over to a folder inside the salesforce/policy_sentry repository instead of my personal one, but that should not be necessary to make this PR. 

## Action items

- [ ] @dgubitosi - update the Terraform readme
- [ ]  @dgubitosi - make the PR to Policy Sentry
- [ ]  @kmcquade - merge that PR, then this one
- [ ]  @kmcquade - create a new issue for Click unit testing
- [ ]  @kmcquade - start the process of moving this Terraform module over there.

Sound good?

**Comment by dgubitosi** [comment]
Sounds good.

I will update the readme in an update to this PR.  I'm not sure if you noticed, but I removed the "create-policy" boolean variable.  Do you want me to restore this behavior?  

I will PR the change to policy_sentry as-is considering that the change is very straight forward.  If I'm not mistaken Click supports flags as --flag/--no-flag so that should be good for minimize as we'll have to use --no-minimize from the terraform module.

**Comment by kmcquade** [comment]
> I'm not sure if you noticed, but I removed the "create-policy" boolean variable. Do you want me to restore this behavior?

I think I created that in the 

> we'll have to use --no-minimize from the terraform module.

Any reason we wouldn't want to minimize the policy? It can make the policies much smaller.

Also, you have to explicitly say you want to minimize the policy by including the `--minimize` flag - by default, it does not minimize the policy

**Comment by dgubitosi** [comment]
Sorry, what was that about the create-policy option?

Minimization is an option in the module.  If you want to retain that behavior, then we need a command line flag for each option. This is a quirk with how the external data source works.  It's an array of strings where spaces get escaped and a null string is not allowed.  This is why I had to let policy_sentry accept minimize -1 for "do not minimize" even though that its the default.

Changing minimize to a simple flag makes this easier, but we still need the "no" version of the flag so we can do this:

locals {
  minimize = var.minimize ? "--minimize" : "--no-minimize"
}

data "external" "policy" {
  program = [ "policy_sentry", "write-policy", "--fmt", "terraform", local.minimize, "--input-file", local_file.template.filename ]
}

I hope that makes sense.

**Comment by kmcquade** [comment]
> Sorry, what was that about the create-policy option?

lol oops. I can't remember what I made that variable for, honestly. Feel free to remove.

> `minimize = var.minimize ? "--minimize" : "--no-minimize"`

What about this instead?

`minimize = var.minimize ? "--minimize" : ""`

**Comment by dgubitosi** [comment]
Terraform doesn't like the empty string in the program array.  I'll redo this test later and paste the Terraform error. 

Here's the empty string error:
`Error: 'program' element 4 is <nil>; a string is required`

However, I don't think this is a problem.  I just looked over the the click documentation:
https://click.palletsprojects.com/en/7.x/options/#boolean-flags

I quickly tested the boolean --shout/--no-shout example.  The default=False parameter makes --no-shout the default so its not required on the command line.

**Comment by kmcquade** [comment]
Maybe we enter a space so it's not empty? `" "` lol

**Comment by dgubitosi** [comment]
I actually tried that! The space produces a Click error.   It gets translated into an escaped space "\  " which Click attempts to parse as an "unexpected" argument.  :(

**Comment by kmcquade** [comment]
That's really weird.

Should we proceed with it as-is for now, without me changing the `--minimize` flag?

Still waiting for that PR in Policy Sentry by the way :)

**Comment by dgubitosi** [comment]
That depends.  I have a draft PR to policy_sentry.  I signed the CLA.  

If you want, I could update my PR to policy_sentry to make --minimize a simple boolean flag (assumes len is always 0), and then update this PR to conform to that change?  Regardless, should I increment the version to 0.9.1 in my PR?

**Comment by kmcquade** [comment]
Yesssss that sounds great! 

I will increment the version soon, but let's leave that out of the PR if that's ok

**Comment by dgubitosi** [comment]
I updated the README.   I set the minimum policy_sentry version to 0.9.1. I removed all references to the double apply, including the demo.  And I removed the "create-policy" option.  I will work on another PR for policy_sentry to convert minimize to a flag.

**Comment by kmcquade** [comment]
@dgubitosi fantastic. Merged!

**Pull request merged**
